// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public final class EmqxExHookProto {
  private EmqxExHookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ProviderLoadedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ProviderLoadedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_LoadedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_LoadedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ProviderUnloadedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ProviderUnloadedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientConnackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientConnackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientConnectedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientConnectedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientDisconnectedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientDisconnectedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientAuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientAuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientCheckAclRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientCheckAclRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientSubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientSubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionCreatedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionCreatedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionSubscribedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionSubscribedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionUnsubscribedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionUnsubscribedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionResumedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionResumedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionDiscardedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionDiscardedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionTakeoveredRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionTakeoveredRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SessionTerminatedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SessionTerminatedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_MessagePublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_MessagePublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_MessageDeliveredRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_MessageDeliveredRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_MessageDroppedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_MessageDroppedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_MessageAckedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_MessageAckedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_EmptySuccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_EmptySuccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ValuedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ValuedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_BrokerInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_BrokerInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_HookSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_HookSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ConnInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ConnInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_ClientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_ClientInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_TopicFilter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_TopicFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_emqx_exhook_v1_SubOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_emqx_exhook_v1_SubOpts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014exhook.proto\022\016emqx.exhook.v1\"C\n\025Provid" +
      "erLoadedRequest\022*\n\006broker\030\001 \001(\0132\032.emqx.e" +
      "xhook.v1.BrokerInfo\"9\n\016LoadedResponse\022\'\n" +
      "\005hooks\030\001 \003(\0132\030.emqx.exhook.v1.HookSpec\"\031" +
      "\n\027ProviderUnloadedRequest\"k\n\024ClientConne" +
      "ctRequest\022*\n\010conninfo\030\001 \001(\0132\030.emqx.exhoo" +
      "k.v1.ConnInfo\022\'\n\005props\030\002 \003(\0132\030.emqx.exho" +
      "ok.v1.Property\"\200\001\n\024ClientConnackRequest\022" +
      "*\n\010conninfo\030\001 \001(\0132\030.emqx.exhook.v1.ConnI" +
      "nfo\022\023\n\013result_code\030\002 \001(\t\022\'\n\005props\030\003 \003(\0132" +
      "\030.emqx.exhook.v1.Property\"H\n\026ClientConne" +
      "ctedRequest\022.\n\nclientinfo\030\001 \001(\0132\032.emqx.e" +
      "xhook.v1.ClientInfo\"[\n\031ClientDisconnecte" +
      "dRequest\022.\n\nclientinfo\030\001 \001(\0132\032.emqx.exho" +
      "ok.v1.ClientInfo\022\016\n\006reason\030\002 \001(\t\"[\n\031Clie" +
      "ntAuthenticateRequest\022.\n\nclientinfo\030\001 \001(" +
      "\0132\032.emqx.exhook.v1.ClientInfo\022\016\n\006result\030" +
      "\002 \001(\010\"\320\001\n\025ClientCheckAclRequest\022.\n\nclien" +
      "tinfo\030\001 \001(\0132\032.emqx.exhook.v1.ClientInfo\022" +
      ">\n\004type\030\002 \001(\01620.emqx.exhook.v1.ClientChe" +
      "ckAclRequest.AclReqType\022\r\n\005topic\030\003 \001(\t\022\016" +
      "\n\006result\030\004 \001(\010\"(\n\nAclReqType\022\013\n\007PUBLISH\020" +
      "\000\022\r\n\tSUBSCRIBE\020\001\"\245\001\n\026ClientSubscribeRequ" +
      "est\022.\n\nclientinfo\030\001 \001(\0132\032.emqx.exhook.v1" +
      ".ClientInfo\022\'\n\005props\030\002 \003(\0132\030.emqx.exhook" +
      ".v1.Property\0222\n\rtopic_filters\030\003 \003(\0132\033.em" +
      "qx.exhook.v1.TopicFilter\"\247\001\n\030ClientUnsub" +
      "scribeRequest\022.\n\nclientinfo\030\001 \001(\0132\032.emqx" +
      ".exhook.v1.ClientInfo\022\'\n\005props\030\002 \003(\0132\030.e" +
      "mqx.exhook.v1.Property\0222\n\rtopic_filters\030" +
      "\003 \003(\0132\033.emqx.exhook.v1.TopicFilter\"G\n\025Se" +
      "ssionCreatedRequest\022.\n\nclientinfo\030\001 \001(\0132" +
      "\032.emqx.exhook.v1.ClientInfo\"\203\001\n\030SessionS" +
      "ubscribedRequest\022.\n\nclientinfo\030\001 \001(\0132\032.e" +
      "mqx.exhook.v1.ClientInfo\022\r\n\005topic\030\002 \001(\t\022" +
      "(\n\007subopts\030\003 \001(\0132\027.emqx.exhook.v1.SubOpt" +
      "s\"[\n\032SessionUnsubscribedRequest\022.\n\nclien" +
      "tinfo\030\001 \001(\0132\032.emqx.exhook.v1.ClientInfo\022" +
      "\r\n\005topic\030\002 \001(\t\"G\n\025SessionResumedRequest\022" +
      ".\n\nclientinfo\030\001 \001(\0132\032.emqx.exhook.v1.Cli" +
      "entInfo\"I\n\027SessionDiscardedRequest\022.\n\ncl" +
      "ientinfo\030\001 \001(\0132\032.emqx.exhook.v1.ClientIn" +
      "fo\"J\n\030SessionTakeoveredRequest\022.\n\nclient" +
      "info\030\001 \001(\0132\032.emqx.exhook.v1.ClientInfo\"Z" +
      "\n\030SessionTerminatedRequest\022.\n\nclientinfo" +
      "\030\001 \001(\0132\032.emqx.exhook.v1.ClientInfo\022\016\n\006re" +
      "ason\030\002 \001(\t\"A\n\025MessagePublishRequest\022(\n\007m" +
      "essage\030\001 \001(\0132\027.emqx.exhook.v1.Message\"s\n" +
      "\027MessageDeliveredRequest\022.\n\nclientinfo\030\001" +
      " \001(\0132\032.emqx.exhook.v1.ClientInfo\022(\n\007mess" +
      "age\030\002 \001(\0132\027.emqx.exhook.v1.Message\"Q\n\025Me" +
      "ssageDroppedRequest\022(\n\007message\030\001 \001(\0132\027.e" +
      "mqx.exhook.v1.Message\022\016\n\006reason\030\002 \001(\t\"o\n" +
      "\023MessageAckedRequest\022.\n\nclientinfo\030\001 \001(\013" +
      "2\032.emqx.exhook.v1.ClientInfo\022(\n\007message\030" +
      "\002 \001(\0132\027.emqx.exhook.v1.Message\"\016\n\014EmptyS" +
      "uccess\"\330\001\n\016ValuedResponse\022:\n\004type\030\001 \001(\0162" +
      ",.emqx.exhook.v1.ValuedResponse.Response" +
      "dType\022\025\n\013bool_result\030\003 \001(\010H\000\022*\n\007message\030" +
      "\004 \001(\0132\027.emqx.exhook.v1.MessageH\000\">\n\rResp" +
      "onsedType\022\014\n\010CONTINUE\020\000\022\n\n\006IGNORE\020\001\022\023\n\017S" +
      "TOP_AND_RETURN\020\002B\007\n\005value\"Q\n\nBrokerInfo\022" +
      "\017\n\007version\030\001 \001(\t\022\020\n\010sysdescr\030\002 \001(\t\022\016\n\006up" +
      "time\030\003 \001(\t\022\020\n\010datetime\030\004 \001(\t\"(\n\010HookSpec" +
      "\022\014\n\004name\030\001 \001(\t\022\016\n\006topics\030\002 \003(\t\"\232\001\n\010ConnI" +
      "nfo\022\014\n\004node\030\001 \001(\t\022\020\n\010clientid\030\002 \001(\t\022\020\n\010u" +
      "sername\030\003 \001(\t\022\020\n\010peerhost\030\004 \001(\t\022\020\n\010sockp" +
      "ort\030\005 \001(\r\022\022\n\nproto_name\030\006 \001(\t\022\021\n\tproto_v" +
      "er\030\007 \001(\t\022\021\n\tkeepalive\030\010 \001(\r\"\333\001\n\nClientIn" +
      "fo\022\014\n\004node\030\001 \001(\t\022\020\n\010clientid\030\002 \001(\t\022\020\n\010us" +
      "ername\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\022\020\n\010peerho" +
      "st\030\005 \001(\t\022\020\n\010sockport\030\006 \001(\r\022\020\n\010protocol\030\007" +
      " \001(\t\022\022\n\nmountpoint\030\010 \001(\t\022\024\n\014is_superuser" +
      "\030\t \001(\010\022\021\n\tanonymous\030\n \001(\010\022\n\n\002cn\030\013 \001(\t\022\n\n" +
      "\002dn\030\014 \001(\t\"q\n\007Message\022\014\n\004node\030\001 \001(\t\022\n\n\002id" +
      "\030\002 \001(\t\022\013\n\003qos\030\003 \001(\r\022\014\n\004from\030\004 \001(\t\022\r\n\005top" +
      "ic\030\005 \001(\t\022\017\n\007payload\030\006 \001(\014\022\021\n\ttimestamp\030\007" +
      " \001(\004\"\'\n\010Property\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t\"(\n\013TopicFilter\022\014\n\004name\030\001 \001(\t\022\013\n\003qo" +
      "s\030\002 \001(\r\"J\n\007SubOpts\022\013\n\003qos\030\001 \001(\r\022\r\n\005share" +
      "\030\002 \001(\t\022\n\n\002rh\030\003 \001(\r\022\013\n\003rap\030\004 \001(\r\022\n\n\002nl\030\005 " +
      "\001(\r2\307\017\n\014HookProvider\022[\n\020OnProviderLoaded" +
      "\022%.emqx.exhook.v1.ProviderLoadedRequest\032" +
      "\036.emqx.exhook.v1.LoadedResponse\"\000\022]\n\022OnP" +
      "roviderUnloaded\022\'.emqx.exhook.v1.Provide" +
      "rUnloadedRequest\032\034.emqx.exhook.v1.EmptyS" +
      "uccess\"\000\022W\n\017OnClientConnect\022$.emqx.exhoo" +
      "k.v1.ClientConnectRequest\032\034.emqx.exhook." +
      "v1.EmptySuccess\"\000\022W\n\017OnClientConnack\022$.e" +
      "mqx.exhook.v1.ClientConnackRequest\032\034.emq" +
      "x.exhook.v1.EmptySuccess\"\000\022[\n\021OnClientCo" +
      "nnected\022&.emqx.exhook.v1.ClientConnected" +
      "Request\032\034.emqx.exhook.v1.EmptySuccess\"\000\022" +
      "a\n\024OnClientDisconnected\022).emqx.exhook.v1" +
      ".ClientDisconnectedRequest\032\034.emqx.exhook" +
      ".v1.EmptySuccess\"\000\022c\n\024OnClientAuthentica" +
      "te\022).emqx.exhook.v1.ClientAuthenticateRe" +
      "quest\032\036.emqx.exhook.v1.ValuedResponse\"\000\022" +
      "[\n\020OnClientCheckAcl\022%.emqx.exhook.v1.Cli" +
      "entCheckAclRequest\032\036.emqx.exhook.v1.Valu" +
      "edResponse\"\000\022[\n\021OnClientSubscribe\022&.emqx" +
      ".exhook.v1.ClientSubscribeRequest\032\034.emqx" +
      ".exhook.v1.EmptySuccess\"\000\022_\n\023OnClientUns" +
      "ubscribe\022(.emqx.exhook.v1.ClientUnsubscr" +
      "ibeRequest\032\034.emqx.exhook.v1.EmptySuccess" +
      "\"\000\022Y\n\020OnSessionCreated\022%.emqx.exhook.v1." +
      "SessionCreatedRequest\032\034.emqx.exhook.v1.E" +
      "mptySuccess\"\000\022_\n\023OnSessionSubscribed\022(.e" +
      "mqx.exhook.v1.SessionSubscribedRequest\032\034" +
      ".emqx.exhook.v1.EmptySuccess\"\000\022c\n\025OnSess" +
      "ionUnsubscribed\022*.emqx.exhook.v1.Session" +
      "UnsubscribedRequest\032\034.emqx.exhook.v1.Emp" +
      "tySuccess\"\000\022Y\n\020OnSessionResumed\022%.emqx.e" +
      "xhook.v1.SessionResumedRequest\032\034.emqx.ex" +
      "hook.v1.EmptySuccess\"\000\022]\n\022OnSessionDisca" +
      "rded\022\'.emqx.exhook.v1.SessionDiscardedRe" +
      "quest\032\034.emqx.exhook.v1.EmptySuccess\"\000\022_\n" +
      "\023OnSessionTakeovered\022(.emqx.exhook.v1.Se" +
      "ssionTakeoveredRequest\032\034.emqx.exhook.v1." +
      "EmptySuccess\"\000\022_\n\023OnSessionTerminated\022(." +
      "emqx.exhook.v1.SessionTerminatedRequest\032" +
      "\034.emqx.exhook.v1.EmptySuccess\"\000\022[\n\020OnMes" +
      "sagePublish\022%.emqx.exhook.v1.MessagePubl" +
      "ishRequest\032\036.emqx.exhook.v1.ValuedRespon" +
      "se\"\000\022]\n\022OnMessageDelivered\022\'.emqx.exhook" +
      ".v1.MessageDeliveredRequest\032\034.emqx.exhoo" +
      "k.v1.EmptySuccess\"\000\022Y\n\020OnMessageDropped\022" +
      "%.emqx.exhook.v1.MessageDroppedRequest\032\034" +
      ".emqx.exhook.v1.EmptySuccess\"\000\022U\n\016OnMess" +
      "ageAcked\022#.emqx.exhook.v1.MessageAckedRe" +
      "quest\032\034.emqx.exhook.v1.EmptySuccess\"\000BI\n" +
      "\016io.emqx.exhookB\017EmqxExHookProtoP\001Z\023emqx" +
      ".io/grpc/exhook\252\002\016Emqx.Exhook.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_emqx_exhook_v1_ProviderLoadedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_emqx_exhook_v1_ProviderLoadedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ProviderLoadedRequest_descriptor,
        new java.lang.String[] { "Broker", });
    internal_static_emqx_exhook_v1_LoadedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_emqx_exhook_v1_LoadedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_LoadedResponse_descriptor,
        new java.lang.String[] { "Hooks", });
    internal_static_emqx_exhook_v1_ProviderUnloadedRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_emqx_exhook_v1_ProviderUnloadedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ProviderUnloadedRequest_descriptor,
        new java.lang.String[] { });
    internal_static_emqx_exhook_v1_ClientConnectRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_emqx_exhook_v1_ClientConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientConnectRequest_descriptor,
        new java.lang.String[] { "Conninfo", "Props", });
    internal_static_emqx_exhook_v1_ClientConnackRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_emqx_exhook_v1_ClientConnackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientConnackRequest_descriptor,
        new java.lang.String[] { "Conninfo", "ResultCode", "Props", });
    internal_static_emqx_exhook_v1_ClientConnectedRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_emqx_exhook_v1_ClientConnectedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientConnectedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", });
    internal_static_emqx_exhook_v1_ClientDisconnectedRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_emqx_exhook_v1_ClientDisconnectedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientDisconnectedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Reason", });
    internal_static_emqx_exhook_v1_ClientAuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_emqx_exhook_v1_ClientAuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientAuthenticateRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Result", });
    internal_static_emqx_exhook_v1_ClientCheckAclRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_emqx_exhook_v1_ClientCheckAclRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientCheckAclRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Type", "Topic", "Result", });
    internal_static_emqx_exhook_v1_ClientSubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_emqx_exhook_v1_ClientSubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientSubscribeRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Props", "TopicFilters", });
    internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Props", "TopicFilters", });
    internal_static_emqx_exhook_v1_SessionCreatedRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_emqx_exhook_v1_SessionCreatedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionCreatedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", });
    internal_static_emqx_exhook_v1_SessionSubscribedRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_emqx_exhook_v1_SessionSubscribedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionSubscribedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Topic", "Subopts", });
    internal_static_emqx_exhook_v1_SessionUnsubscribedRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_emqx_exhook_v1_SessionUnsubscribedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionUnsubscribedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Topic", });
    internal_static_emqx_exhook_v1_SessionResumedRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_emqx_exhook_v1_SessionResumedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionResumedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", });
    internal_static_emqx_exhook_v1_SessionDiscardedRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_emqx_exhook_v1_SessionDiscardedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionDiscardedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", });
    internal_static_emqx_exhook_v1_SessionTakeoveredRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_emqx_exhook_v1_SessionTakeoveredRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionTakeoveredRequest_descriptor,
        new java.lang.String[] { "Clientinfo", });
    internal_static_emqx_exhook_v1_SessionTerminatedRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_emqx_exhook_v1_SessionTerminatedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SessionTerminatedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Reason", });
    internal_static_emqx_exhook_v1_MessagePublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_emqx_exhook_v1_MessagePublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_MessagePublishRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_emqx_exhook_v1_MessageDeliveredRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_emqx_exhook_v1_MessageDeliveredRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_MessageDeliveredRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Message", });
    internal_static_emqx_exhook_v1_MessageDroppedRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_emqx_exhook_v1_MessageDroppedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_MessageDroppedRequest_descriptor,
        new java.lang.String[] { "Message", "Reason", });
    internal_static_emqx_exhook_v1_MessageAckedRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_emqx_exhook_v1_MessageAckedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_MessageAckedRequest_descriptor,
        new java.lang.String[] { "Clientinfo", "Message", });
    internal_static_emqx_exhook_v1_EmptySuccess_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_emqx_exhook_v1_EmptySuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_EmptySuccess_descriptor,
        new java.lang.String[] { });
    internal_static_emqx_exhook_v1_ValuedResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_emqx_exhook_v1_ValuedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ValuedResponse_descriptor,
        new java.lang.String[] { "Type", "BoolResult", "Message", "Value", });
    internal_static_emqx_exhook_v1_BrokerInfo_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_emqx_exhook_v1_BrokerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_BrokerInfo_descriptor,
        new java.lang.String[] { "Version", "Sysdescr", "Uptime", "Datetime", });
    internal_static_emqx_exhook_v1_HookSpec_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_emqx_exhook_v1_HookSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_HookSpec_descriptor,
        new java.lang.String[] { "Name", "Topics", });
    internal_static_emqx_exhook_v1_ConnInfo_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_emqx_exhook_v1_ConnInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ConnInfo_descriptor,
        new java.lang.String[] { "Node", "Clientid", "Username", "Peerhost", "Sockport", "ProtoName", "ProtoVer", "Keepalive", });
    internal_static_emqx_exhook_v1_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_emqx_exhook_v1_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_ClientInfo_descriptor,
        new java.lang.String[] { "Node", "Clientid", "Username", "Password", "Peerhost", "Sockport", "Protocol", "Mountpoint", "IsSuperuser", "Anonymous", "Cn", "Dn", });
    internal_static_emqx_exhook_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_emqx_exhook_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_Message_descriptor,
        new java.lang.String[] { "Node", "Id", "Qos", "From", "Topic", "Payload", "Timestamp", });
    internal_static_emqx_exhook_v1_Property_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_emqx_exhook_v1_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_Property_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_emqx_exhook_v1_TopicFilter_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_emqx_exhook_v1_TopicFilter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_TopicFilter_descriptor,
        new java.lang.String[] { "Name", "Qos", });
    internal_static_emqx_exhook_v1_SubOpts_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_emqx_exhook_v1_SubOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_emqx_exhook_v1_SubOpts_descriptor,
        new java.lang.String[] { "Qos", "Share", "Rh", "Rap", "Nl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
